Added validation logic and impl. Cloneable to BankAccount.java
JZ-FSDev/Bank pull request #2
Opened 2021-12-27 21:17 UTC by DZ-FSDev

Added validation logic and implemented java.lang.Cloneable. Added javadoc.
Consider moving account numbering logic into BankAccount.java from Bank.java to enforce unique constraint.

2021-12-27 21:28 UTC, JZ-FSDev requested changes
Repeated validation logic should be moved laterally to a private static method.

2021-12-28 17:44 UTC, DZ-FSDev commented
Repeated validation logic moved laterally to 2 private static methods. Updated javadoc.

2021-12-28 17:45 UTC, DZ-FSDev reviewed
Found validation logic to move laterally.

2021-12-28 17:50 UTC, JZ-FSDev approved these changes

2021-12-28 17:51 UTC, merged